language: ruby
rvm:
  - 2.3.3

script: bundle exec jekyll build && bundle exec htmlproofer ./_site --disable-external --url-swap "^\/genderkit\/:/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES: true

sudo: false
